"""change_property_media_url_to_text

Revision ID: ae483ab1cb20
Revises: 9599b1907258
Create Date: 2026-06-16 07:11:10.012522
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ae483ab1cb20'
down_revision: Union[str, None] = '9599b1907258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_media', 'url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property_media', 'url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
