from __future__ import annotations

from abc import ABC, abstractmethod
from uuid import UUID

from app.domain.entities.activity import Activity
from app.domain.entities.activity_provider_profile import ActivityProviderProfile


class ActivityRepository(ABC):
    @abstractmethod
    async def create_profile(self, profile: ActivityProviderProfile) -> ActivityProviderProfile: ...
    @abstractmethod
    async def get_profile_by_user_id(self, user_id: UUID) -> ActivityProviderProfile | None: ...
    @abstractmethod
    async def get_profile_by_id(self, profile_id: UUID) -> ActivityProviderProfile | None: ...
    @abstractmethod
    async def update_profile(self, profile: ActivityProviderProfile) -> ActivityProviderProfile: ...
    @abstractmethod
    async def create_activity(self, activity: Activity) -> Activity: ...
    @abstractmethod
    async def get_activity_by_id(self, activity_id: UUID) -> Activity | None: ...
    @abstractmethod
    async def get_activities_by_provider(self, provider_profile_id: UUID, offset: int = 0, limit: int = 20) -> tuple[list[Activity], int]: ...
    @abstractmethod
    async def list_activities(self, city_id: UUID | None = None, offset: int = 0, limit: int = 20) -> tuple[list[Activity], int]: ...
    @abstractmethod
    async def update_activity(self, activity: Activity) -> Activity: ...
    @abstractmethod
    async def delete_activity(self, activity_id: UUID) -> None: ...
    @abstractmethod
    async def list_providers(self, offset: int = 0, limit: int = 20) -> tuple[list[ActivityProviderProfile], int]: ...
