from __future__ import annotations

from abc import ABC, abstractmethod
from uuid import UUID

from app.domain.entities.agency_profile import AgencyProfile
from app.domain.entities.tour_package import TourPackage


class AgencyRepository(ABC):
    @abstractmethod
    async def create_profile(self, profile: AgencyProfile) -> AgencyProfile: ...
    @abstractmethod
    async def get_profile_by_user_id(self, user_id: UUID) -> AgencyProfile | None: ...
    @abstractmethod
    async def get_profile_by_id(self, profile_id: UUID) -> AgencyProfile | None: ...
    @abstractmethod
    async def update_profile(self, profile: AgencyProfile) -> AgencyProfile: ...
    @abstractmethod
    async def create_tour_package(self, pkg: TourPackage) -> TourPackage: ...
    @abstractmethod
    async def get_tour_package_by_id(self, pkg_id: UUID) -> TourPackage | None: ...
    @abstractmethod
    async def get_tour_packages_by_agency(self, agency_profile_id: UUID, offset: int = 0, limit: int = 20) -> tuple[list[TourPackage], int]: ...
    @abstractmethod
    async def list_tour_packages(self, offset: int = 0, limit: int = 20) -> tuple[list[TourPackage], int]: ...
    @abstractmethod
    async def update_tour_package(self, pkg: TourPackage) -> TourPackage: ...
    @abstractmethod
    async def delete_tour_package(self, pkg_id: UUID) -> None: ...
    @abstractmethod
    async def list_agencies(self, offset: int = 0, limit: int = 20) -> tuple[list[AgencyProfile], int]: ...
