from __future__ import annotations

from abc import ABC, abstractmethod
from uuid import UUID

from app.domain.entities.guide_profile import GuideProfile
from app.domain.entities.tour import Tour


class GuideRepository(ABC):
    @abstractmethod
    async def create_profile(self, profile: GuideProfile) -> GuideProfile: ...
    @abstractmethod
    async def get_profile_by_user_id(self, user_id: UUID) -> GuideProfile | None: ...
    @abstractmethod
    async def get_profile_by_id(self, profile_id: UUID) -> GuideProfile | None: ...
    @abstractmethod
    async def update_profile(self, profile: GuideProfile) -> GuideProfile: ...
    @abstractmethod
    async def create_tour(self, tour: Tour) -> Tour: ...
    @abstractmethod
    async def get_tour_by_id(self, tour_id: UUID) -> Tour | None: ...
    @abstractmethod
    async def get_tours_by_guide(self, guide_profile_id: UUID, offset: int = 0, limit: int = 20) -> tuple[list[Tour], int]: ...
    @abstractmethod
    async def list_tours(self, city_id: UUID | None = None, offset: int = 0, limit: int = 20) -> tuple[list[Tour], int]: ...
    @abstractmethod
    async def update_tour(self, tour: Tour) -> Tour: ...
    @abstractmethod
    async def delete_tour(self, tour_id: UUID) -> None: ...
    @abstractmethod
    async def list_guides(self, offset: int = 0, limit: int = 20) -> tuple[list[GuideProfile], int]: ...
